[versions]
agp = "8.11.2"
appUpdate = "2.1.0"
billing = "8.3.0"
credentials = "1.5.0"
firebaseBom = "33.3.0"
#fotoapparat = "2.7.0"
googleid = "1.2.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
material = "1.14.0"
activity = "1.13.0"
constraintlayout = "2.1.4"
googleGmsGoogleServices = "4.4.2"
firebaseDatabase = "21.0.0"
playServicesLocation = "21.3.0"
sdpAndroid = "1.1.1"
firebaseFirestore = "25.1.0"
googleAndroidLibrariesMapsplatformSecretsGradlePlugin = "2.0.1"
playServicesMaps = "19.0.0"
timerangepicker = "1.0.0"
volley = "1.2.1"
#ucrop = "2.2.10"

[libraries]
app-update = { module = "com.google.android.play:app-update", version.ref = "appUpdate" }
billing = { module = "com.android.billingclient:billing", version.ref = "billing" }
credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-storage = { module = "com.google.firebase:firebase-storage" }
#fotoapparat = { module = "io.fotoapparat:fotoapparat", version.ref = "fotoapparat" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroid" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
timerangepicker = { module = "nl.joery.timerangepicker:timerangepicker", version.ref = "timerangepicker" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }
#ucrop = { module = "com.github.yalantis:ucrop", version.ref = "ucrop" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
google-android-libraries-mapsplatform-secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "googleAndroidLibrariesMapsplatformSecretsGradlePlugin" }

